services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
