services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      # If you browse from INSIDE the VM, leave as localhost.
      # If you browse from your host machine, replace with the VM's IP.
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
